RBAC for admin apis
roverxio/toadplatform pull request #323
Opened 2023-09-01 11:41 UTC by viv-defy

2023-09-01 13:06 UTC, ska1296 requested changes

2023-09-01 13:06 UTC, ska1296 commented on bundler/src/handlers/admin.rs
> +    if !is_admin(get_user(req)) {
if you always check for "not" condition, I think it's better to change your function name and return value

2023-09-01 13:06 UTC, ska1296 commented on bundler/src/handlers/admin.rs
> +    admins.contains(&&*user)
you can just do a string contains here. No need to convert it to an array.

2023-09-01 13:28 UTC, ska1296 commented on bundler/src/handlers/admin.rs
> +    admins.contains(&&*user)
```suggestion
    let admins = admins_env.split(",").collect::<Vec<String>>();
    admins.contains(&user)
```

2023-09-04 05:05 UTC, vishnukvnvv commented on bundler/src/handlers/admin.rs
> +    let admins_env = std::env::var("ADMIN").expect("ADMIN env variable not set");
Can be fetched once at server start and reused

2023-09-04 05:13 UTC, vishnukvnvv commented
@viv-defy, Update your local branch from the release branch

2023-09-04 06:46 UTC, ska1296 commented on bundler/src/server.rs
> +
move admin as a variable to "settings" struct instead of passing it around to services

2023-09-04 06:46 UTC, vishnukvnvv commented on bundler/src/services/admin_service.rs
> +    pub admins: Vec<String>,
Remove this from the service layer and add it in config/settings

2023-09-04 09:47 UTC, ska1296 approved these changes

2023-09-04 09:49 UTC, vishnukvnvv approved these changes

2023-09-04 09:53 UTC, merged