Sync pipelines skeleton
roverxio/toadplatform pull request #344
Opened 2023-09-05 13:00 UTC by viv-defy

2023-09-05 13:49 UTC, ska1296 commented on sync-pipelines-rust/src/config.toml
rename the file to config.toml.example

2023-09-05 13:49 UTC, ska1296 commented on sync-pipelines-rust/src/constants.rs
> +impl Constants {
make it an enum. refer to bundler's code

2023-09-06 05:28 UTC, vishnukvnvv requested changes

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/Cargo.toml
> +sqlx-type = "0.3.12"
Is this needed?

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/config.rs
> +use sqlx::types::chrono::NaiveTime;
Add `chrono` create and use from it

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/config.rs
> +    transactions: NaiveTime,
```suggestion
    transactions: DateTime<Utc>,
```

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/config.rs
> +    transactions: NaiveTime,
Follow for all timestamp fileds

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/config.rs
> +}
Does not match the example config file

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/main.rs
> +    // define CONFIG and POOL
Initialize config only in the block

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/main.rs
> +    // read command line arguments
DB pool connection initialization should be done here

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/sync_transfers.rs
> +}
Create user transaction dao under `./sync-pipelines-rust/dao/`

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/sync_transfers.rs
> +}
Move this to user transaction dao implementation

2023-09-06 05:28 UTC, vishnukvnvv commented on sync-pipelines-rust/src/sync_transfers.rs
> +pub fn get_transfers(from_table: Table) -> Vec<Transfer> {
Return type should be token transfers

2023-09-06 10:39 UTC, vishnukvnvv requested changes

2023-09-06 10:39 UTC, vishnukvnvv commented on sync-pipelines-rust/src/config.rs
> +}
Not needed, as its picked form db

2023-09-06 10:42 UTC, vishnukvnvv requested changes

2023-09-06 10:42 UTC, vishnukvnvv commented on sync-pipelines-rust/config-example.toml
> +process_pool = 20
Not needed

2023-09-07 12:32 UTC, ska1296 requested changes

2023-09-07 12:32 UTC, ska1296 commented on sync-pipelines-rust/src/utils/constants.rs
you can rename this to env.ts

2023-09-07 12:32 UTC, ska1296 commented on sync-pipelines-rust/src/utils/constants.rs
> +pub enum Constants {
These are no longer constants. Now these are very specific env properties.

2023-09-07 12:32 UTC, ska1296 commented on sync-pipelines-rust/src/utils/constants.rs
move this file to models/config or models/environment

2023-09-07 12:45 UTC, ska1296 requested changes

2023-09-07 12:45 UTC, ska1296 commented on sync-pipelines-rust/config-example.toml
> +[last_sync_time]
```suggestion
[last_sync_time.files]
```
@horsey-defy what do you think?

2023-09-07 12:45 UTC, ska1296 commented on sync-pipelines-rust/src/main.rs
> +    sync_user_transactions(Table::from(""), &pool);
better to call it `sync_erc20_transfers` since that's what will happen here

2023-09-07 12:45 UTC, ska1296 commented on sync-pipelines-rust/src/sync_transfers.rs
> +    };
It's better to move this to main instead of doing it here. Plus, the last sync time might be different for token_transfers and transactions. This logic won't do well

2023-09-08 10:25 UTC, merged