improve the deploy scripts
roverxio/toadplatform pull request #355
Opened 2023-09-06 11:40 UTC by viv-defy

2023-09-06 11:55 UTC, ska1296 commented on contracts/script/deploy_local.sh
> +# shellcheck disable=SC2164
??

2023-09-06 11:55 UTC, ska1296 commented on contracts/script/deploy_local.sh
> +cd $(dirname $(pwd))
do you need both? pwd and $0

2023-09-07 04:52 UTC, viv-defy commented on contracts/script/deploy_local.sh
> +# shellcheck disable=SC2164
The IDE was throwing up warnings. So I used these shell checks, suggested by the IDE, for suppressing the warnings

2023-09-07 04:57 UTC, viv-defy commented on contracts/script/deploy_local.sh
> +cd $(dirname $(pwd))
$0 gives the path to the deploy script, from the directory that the bash command is run from. We can then use it to move to the parent directory.
But, this is an issue when we run it from contracts/scripts dir. $0 gives us `.`. We cannot move to the parent directory of `.`. So, we have to use pwd to get the full path

2023-09-07 06:20 UTC, ska1296 commented on contracts/script/deploy_local.sh
> +# shellcheck disable=SC2164
don't suppress warning. address them.

2023-09-07 06:30 UTC, ska1296 requested changes

2023-09-07 06:30 UTC, ska1296 commented on contracts/script/deploy_local.sh
> +  if [[ "$line" == "Error:"* ]]; then
I always get this error irrespective of anvil's status. This is misleading.

2023-09-12 13:32 UTC, ska1296 approved these changes

2023-09-14 11:10 UTC, merged