Config and DB initialization
roverxio/toadplatform pull request #383
Opened 2023-09-08 11:54 UTC by viv-defy

2023-09-11 05:50 UTC, viv-defy commented
### Testing

- Create Config.toml using Config-example.toml
- Add the following code section after line 25, `let last_sync_time = ...` in main.rs
  ```
  println!(
        " {}\n {}\n {}\n {}\n {}\n {}\n {}",
        CONFIG.get_chain(),
        CONFIG.get_native_currency(),
        CONFIG.get_transaction_id_prefix(),
        CONFIG
            .get_last_sync_file_token_transfers()
            .to_string_lossy(),
        CONFIG.get_last_sync_file_transactions().to_string_lossy(),
        CONFIG.get_last_sync_time_token_transfers(),
        CONFIG.get_last_sync_time_transactions()
    );
    ```
- run: `cargo run <table>`
Table can be
- token_transfers
- transactions

2023-09-11 10:19 UTC, ska1296 requested changes

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/settings.rs
> +    pub fn get_transaction_id_prefix(&self) -> &String {
Why are you returning a `&String` everywhere? Why not a String or a &str?

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/settings.rs
> +            .add_source(File::with_name(CONFIG_FILE_PATH).required(false))
```suggestion
            .add_source(File::with_name(CONFIG_FILE_PATH).required(true))
```
we need a file for config

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/utils/table.rs
> +                warn!("Invalid table argument");
error, if you are exiting

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/utils/table.rs
>              transfers if transfers == "token_transfers".to_string() => Table::TokenTransfers,
why do you need to convert "token_transfers" to_string here?

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
>  pub struct Utils {}
why?

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
> +const DATETIME_PATTERN: &str = "%Y-%m-%d %H:%M:%S %z";
consider moving it inside the impl block if it is only used here

2023-09-11 10:19 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
> +    pub fn get_last_synced_time(table: Table) -> DateTime<Utc> {
I think it is better to move this to Settings.rs

2023-09-11 10:55 UTC, ska1296 requested changes

2023-09-11 10:55 UTC, ska1296 commented on sync-pipelines-rust/config-example.toml
> +transactions = 0
why keep this at 0? It's still an invalid date, right?

2023-09-11 11:28 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
>  pub struct Utils {}
because we are writing impl

2023-09-11 11:29 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
> +    pub fn get_last_synced_time(table: Table) -> DateTime<Utc> {
then write would happen in one place and read would happen in another.

2023-09-12 09:40 UTC, viv-defy commented on sync-pipelines-rust/config-example.toml
> +transactions = 0
Changed transactions' last_sync_time and token_transfers' last_sync_block_number to int type as per the schema: https://github.com/blockchain-etl/ethereum-etl/blob/develop/docs/schema.md#transactionscsv

2023-09-13 06:47 UTC, ska1296 commented
There are major changes in #391. This PR can be closed and ignored.

2023-09-13 06:47 UTC, closed without merging