rust pipeline database queries
roverxio/toadplatform pull request #391
Opened 2023-09-11 14:11 UTC by viv-defy

…btain user_transactions

2023-09-13 07:25 UTC, vishnukvnvv commented on sync-pipelines-rust/src/utils/table.rs
> +            transactions if transactions == "transactions" => Table::Transactions,
Is this similar to string matching ?

2023-09-13 07:32 UTC, vishnukvnvv requested changes

2023-09-13 07:32 UTC, vishnukvnvv commented on sync-pipelines-rust/src/db/transactions.rs
> +impl Transactions {
Avoid multiple implementations

2023-09-13 11:08 UTC, viv-defy commented on sync-pipelines-rust/src/utils/table.rs
> +            transactions if transactions == "transactions" => Table::Transactions,
yes

2023-09-14 09:07 UTC, ska1296 requested changes

2023-09-14 09:07 UTC, ska1296 commented on sync-pipelines-rust/src/db/user_transactions.rs
> +    pub metadata: Value,
missed exponent?

2023-09-14 09:07 UTC, ska1296 commented on sync-pipelines-rust/src/utils/table.rs
> +            transactions if transactions == "transactions" => Table::Transactions,
```rust
match table.as_str() {
            "token_transfers" => Table::TokenTransfers,
            "transactions" => Table::Transactions,
            ..
}
```

you could just done this

2023-09-14 09:07 UTC, ska1296 commented on sync-pipelines-rust/src/main.rs
> +            let block_number = Utils::get_last_synced_block_token_transfers();
maybe move each handling to a separate file?

2023-09-14 09:22 UTC, ska1296 approved these changes

2023-09-14 09:22 UTC, ska1296 commented on sync-pipelines-rust/src/utils/utils.rs
> +    pub fn update_last_synced_block_token_transfers(last_sync_block: i64) {
let's move it to LastSync type instead of a utils file

2023-09-15 05:44 UTC, ska1296 requested changes

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/connection.rs
> +                match connection {
instead of match, try using `connection.unwrap_or_else`

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/token_transfers.rs
> +            "SELECT lower(from_address) from_address, lower(to_address) to_address, value, \
the point of using alias was also for select statements, not just comparison

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/token_transfers.rs
> +            JOIN users u ON lower(t.to_address) = u.wallet_address \
you can choose to not use "lower" in this query when dealing with token_transfers table

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/transactions.rs
> +            "SELECT lower(from_address) from_address, lower(to_address) to_address, value, \
use table alias in select statements too

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/transactions.rs
> +            JOIN users usr ON lower(txn.to_address) = usr.wallet_address \
you can skip "lower" when dealing with transactions table

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/db/transactions.rs
> +            JOIN (SELECT exponent FROM token_metadata WHERE chain = $2 and contract_address = $3) met ON true \
you can choose to go with "symbol" or "token_type" (as native) instead of all 0s.
I think symbol would be a better choice since it is a part of the config

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/utils/last_sync.rs
belongs to "model", not utils

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/utils/last_sync.rs
> +            Ok(time) => time.parse::<i64>().unwrap(),
we are not dealing with "time" anymore

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/utils/last_sync.rs
> +}
can this not be a single function with 2 parameters?

2023-09-15 05:44 UTC, ska1296 commented on sync-pipelines-rust/src/utils/last_sync.rs
> +    pub fn update_last_synced_block_transactions(last_sync_time: i64) {
we are dealing with blocks, not time

2023-09-15 05:48 UTC, vishnukvnvv commented on sync-pipelines-rust/src/settings.rs
> +        self.last_sync.block.token_transfers.clone()
```suggestion
        self.last_sync.block.token_transfers
```

2023-09-15 06:14 UTC, vishnukvnvv requested changes

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/main.rs
> +const LOG_CONFIG: &str = "log_config.yaml";
```suggestion
const LOG_CONFIG: &str = "./log_config.yaml";
```

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/services/sync_user_transactions.rs
> +        if token_transfers.clone().len() == 0 {
```suggestion
        if token_transfers.len() == 0 {
```

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/services/sync_user_transactions.rs
> +        if transactions.clone().len() == 0 {
```suggestion
        if transactions.len() == 0 {
```

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/db/user_transactions.rs
> +    pub fn from_token_transfers(transfers: Vec<TokenTransfers>) -> Vec<UserTransaction> {
```suggestion
    pub fn from_token_transfers(token_transfers: Vec<TokenTransfers>) -> Vec<UserTransaction> {
```

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/db/user_transactions.rs
> +        user_transactions
```suggestion
        token_transfers.into_iter().map(UserTransaction::from).collect()
```

2023-09-15 06:14 UTC, vishnukvnvv commented on sync-pipelines-rust/src/db/user_transactions.rs
> +        user_transactions
```suggestion
        transfers.into_iter().map(UserTransaction::from).collect()
```

2023-09-15 06:20 UTC, vishnukvnvv commented
@viv-defy Don't use exit every where, pass the error to the caller functions

2023-09-15 06:31 UTC, vishnukvnvv requested changes

2023-09-15 06:31 UTC, vishnukvnvv commented on sync-pipelines-rust/src/models/environment/mod.rs
> +pub mod env;
Not used

2023-09-15 06:31 UTC, vishnukvnvv commented on sync-pipelines-rust/src/models/last_sync.rs
> +    }
Can be one function

2023-09-15 10:08 UTC, vishnukvnvv requested changes

2023-09-15 10:08 UTC, vishnukvnvv commented on sync-pipelines-rust/src/main.rs
> +    };
Initiate db connection after table argument validation

2023-09-15 10:14 UTC, vishnukvnvv requested changes

2023-09-15 10:14 UTC, vishnukvnvv commented on sync-pipelines-rust/README.md
> +2. Copy `config-example.toml` into `Config.toml` and fill in the details
Step to add env for db connection

2023-09-15 10:14 UTC, vishnukvnvv commented on sync-pipelines-rust/README.md
> +1. The script reads the last synced block number from the `transaction_last_sync_block.txt` file for transactions and from `erc20_last_sync_block.txt` file for token_transfers. If the file is not pre
```suggestion
1. The script reads the last synced block number from the `transaction_last_sync_block.txt` file for transactions and from `erc20_last_sync_block.txt` file for token_transfers. If the file is not present, it starts from the block number mentioned in config file
```

2023-09-15 10:14 UTC, vishnukvnvv commented on sync-pipelines-rust/README.md
> +5. Ideally, the script should be run as a cron job to sync the data periodically. This is written to be run as a cron job every minute
Not needed

2023-09-19 11:05 UTC, ska1296 requested changes

2023-09-19 11:05 UTC, ska1296 commented on sync-pipelines-rust/src/db/user_transactions.rs
> +            exponent: 0,
while referring to the python scripts I realised that exponent is not a part of the pipelines at all. It is application logic exclusively.

2023-09-19 11:05 UTC, ska1296 commented
Not continuing review

2023-09-26 05:31 UTC, vishnukvnvv commented
Merging this and creating a new PR to fix the existing issues and resolve comments

2023-09-26 05:31 UTC, merged