update README.md
roverxio/toadplatform pull request #396
Opened 2023-09-12 11:02 UTC by viv-defy

2023-09-12 13:12 UTC, horsey-defy approved these changes

2023-09-12 14:15 UTC, ska1296 requested changes

2023-09-12 14:15 UTC, ska1296 commented on README.md
> +   1. By default, the server uses "Staging.toml" as the config file. If you want to use a different config file, set the `RUN_ENV` environment variable to the path of the config file. `RUN_ENV` can b
we use Development.toml be default

2023-09-12 14:15 UTC, ska1296 commented on README.md
> +4. Run
also need to run migrations before this

2023-09-12 14:15 UTC, ska1296 commented on README.md
> +- git clone https://github.com/Club-Defy/roverx-rpc
1. this needs to be the very first step. It can then be removed from everywhere else.
2. Repo name is wrong

2023-09-12 14:35 UTC, ska1296 requested changes

2023-09-12 14:35 UTC, ska1296 commented on README.md
> +MSRP: `rustc 1.71.0 (8ede3aae2 2023-07-12)`
would be better to make a pre requisite section and put this there, alongside foundry and postgres

2023-09-12 14:35 UTC, ska1296 commented on README.md
> +On successful deployment, you can find the deployed contract addresses, `signer/owner` address and a `key`. Use this info to populate the `bundler/.env` and `bundler/config/*.toml` files, as directed
```suggestion
On successful deployment, you can find the deployed contract addresses, `signer/owner` address and a `key`. Use this information to populate the `bundler/.env` and `bundler/config/*.toml` files, as directed in the following section
```

better to be formal, I believe?

2023-09-12 14:35 UTC, ska1296 commented on README.md
> +1. Set up a postgres database
Is it worth mentioning that we use version 13?

2023-09-12 15:02 UTC, ska1296 requested changes

2023-09-12 15:02 UTC, ska1296 commented on README.md
> +MSRP: `rustc 1.71.0 (8ede3aae2 2023-07-12)`
Shouldn't this be "MSV"?

2023-09-14 09:30 UTC, ska1296 commented
already merged to main in #401 and #403

2023-09-14 09:30 UTC, ska1296 commented
already merged to main in https://github.com/roverxio/toadplatform/pull/401 and https://github.com/roverxio/toadplatform/pull/403

2023-09-14 09:30 UTC, closed without merging